version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-73-247-67.compute-1.amazonaws.com
            database: d10ge36fpr0ah5
            # schema: public
            user: djmwciwlibnpon
            password: f20f3cc9237e89a76f67fd4999277085107c36236d926055c68f37b03eb9d78f
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: false